-- Generated by scripts/upgrade-fixture.mjs from v0.42.0 (a9659ac983f3d1382ba23c61dbd5ef356cd09fcc). Do not edit by hand.
-- The provider key below is encrypted under the throwaway FIXTURE_MASTER_KEY in that script.
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE SCHEMA drizzle;

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;

SET default_tablespace = '';

SET default_table_access_method = heap;

CREATE TABLE drizzle.__drizzle_migrations (
    id integer NOT NULL,
    hash text NOT NULL,
    created_at bigint
);

CREATE SEQUENCE drizzle.__drizzle_migrations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE drizzle.__drizzle_migrations_id_seq OWNED BY drizzle.__drizzle_migrations.id;

CREATE TABLE public.account (
    id text NOT NULL,
    account_id text NOT NULL,
    provider_id text NOT NULL,
    user_id text NOT NULL,
    access_token text,
    refresh_token text,
    id_token text,
    access_token_expires_at timestamp without time zone,
    refresh_token_expires_at timestamp without time zone,
    scope text,
    password text,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);

CREATE TABLE public.attached_folders (
    id text NOT NULL,
    user_id text NOT NULL,
    session_key text NOT NULL,
    kind text NOT NULL,
    name text NOT NULL,
    host_path text,
    read_only boolean DEFAULT true NOT NULL,
    state jsonb,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    sync_lease jsonb
);

CREATE TABLE public.audit_events (
    id text NOT NULL,
    space_id text NOT NULL,
    actor jsonb NOT NULL,
    action text NOT NULL,
    subject_type text NOT NULL,
    subject_id text NOT NULL,
    payload jsonb,
    created_at timestamp without time zone DEFAULT now()
);

CREATE TABLE public.audit_log (
    id text NOT NULL,
    actor_id text,
    action text NOT NULL,
    target_type text,
    target_key text,
    detail jsonb DEFAULT '{}'::jsonb,
    created_at timestamp without time zone DEFAULT now()
);

CREATE TABLE public.automation_webhook_deliveries (
    automation_id text NOT NULL,
    idempotency_key text NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.automations (
    id text NOT NULL,
    user_id text NOT NULL,
    project_id text,
    title text NOT NULL,
    prompt text NOT NULL,
    model text,
    trigger jsonb NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    next_run_at timestamp without time zone,
    last_run_at timestamp without time zone,
    last_task_id text,
    consecutive_failures integer DEFAULT 0 NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    disabled_reason text,
    webhook_token text,
    max_runs_per_day integer,
    runs_day date,
    runs_today integer DEFAULT 0 NOT NULL,
    skipped_today integer DEFAULT 0 NOT NULL,
    thread_mode text DEFAULT 'fresh'::text NOT NULL,
    thread_chat_id text,
    run_when text,
    last_skip jsonb,
    quiet_today integer DEFAULT 0 NOT NULL,
    notify_mode text DEFAULT 'always'::text NOT NULL,
    deliver_telegram boolean DEFAULT true NOT NULL
);

CREATE TABLE public.capability_policies (
    id text NOT NULL,
    scope text DEFAULT 'system'::text NOT NULL,
    user_id text,
    project_id text,
    capability_type text NOT NULL,
    capability_key text NOT NULL,
    effect text NOT NULL,
    created_by text,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    revision bigint DEFAULT 0 NOT NULL,
    CONSTRAINT ck_capability_policies_subject CHECK ((((scope = 'system'::text) AND (user_id IS NULL) AND (project_id IS NULL)) OR ((scope = 'user'::text) AND (user_id IS NOT NULL) AND (project_id IS NULL)) OR ((scope = 'project'::text) AND (project_id IS NOT NULL) AND (user_id IS NULL))))
);

CREATE TABLE public.chat_secrets (
    id text NOT NULL,
    chat_id text NOT NULL,
    user_id text NOT NULL,
    name text NOT NULL,
    value_enc text NOT NULL,
    created_at timestamp without time zone DEFAULT now()
);

CREATE TABLE public.chats (
    id text NOT NULL,
    user_id text NOT NULL,
    project_id text,
    title text,
    model text,
    pinned boolean DEFAULT false,
    archived boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    active_leaf_id text,
    source text DEFAULT 'web'::text,
    visibility text DEFAULT 'private'::text NOT NULL,
    share_token text,
    last_read_at timestamp without time zone,
    think_amount text
);

CREATE TABLE public.claim_evidence (
    id text NOT NULL,
    claim_id text NOT NULL,
    relation text DEFAULT 'supports'::text NOT NULL,
    fragment_id text,
    message_id text,
    quote_snapshot text,
    locator_snapshot jsonb,
    created_at timestamp without time zone DEFAULT now()
);

CREATE TABLE public.knowledge_fragments (
    id text NOT NULL,
    version_id text NOT NULL,
    ordinal integer NOT NULL,
    text text NOT NULL,
    language text,
    locator jsonb NOT NULL
);

CREATE TABLE public.knowledge_source_versions (
    id text NOT NULL,
    source_id text NOT NULL,
    sha256 text NOT NULL,
    observed_at timestamp without time zone DEFAULT now() NOT NULL,
    parser jsonb DEFAULT '{}'::jsonb NOT NULL,
    representations jsonb DEFAULT '{}'::jsonb NOT NULL,
    status text DEFAULT 'ingesting'::text NOT NULL,
    error text,
    superseded_at timestamp without time zone
);

CREATE TABLE public.knowledge_sources (
    id text NOT NULL,
    space_id text NOT NULL,
    title text NOT NULL,
    origin jsonb NOT NULL,
    labels jsonb DEFAULT '[]'::jsonb NOT NULL,
    created_by text NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    deleted_at timestamp without time zone
);

CREATE TABLE public.link_codes (
    code text NOT NULL,
    user_id text NOT NULL,
    expires_at timestamp without time zone NOT NULL
);

CREATE TABLE public.manage_pending (
    id text NOT NULL,
    user_id text NOT NULL,
    project_id text,
    kind text NOT NULL,
    payload jsonb NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    expires_at timestamp without time zone NOT NULL,
    consumed_at timestamp without time zone
);

CREATE TABLE public.mcp_oauth_clients (
    server_id text NOT NULL,
    client_info text NOT NULL,
    created_at timestamp without time zone DEFAULT now()
);

CREATE TABLE public.mcp_oauth_states (
    state text NOT NULL,
    user_id text NOT NULL,
    server_id text NOT NULL,
    code_verifier text NOT NULL,
    created_at timestamp without time zone DEFAULT now()
);

CREATE TABLE public.mcp_oauth_tokens (
    id text NOT NULL,
    user_id text NOT NULL,
    server_id text NOT NULL,
    tokens text NOT NULL,
    account text,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);

CREATE TABLE public.mcp_servers (
    id text NOT NULL,
    scope text NOT NULL,
    user_id text,
    project_id text,
    name text NOT NULL,
    transport text DEFAULT 'http'::text NOT NULL,
    url text,
    command text,
    args jsonb DEFAULT '[]'::jsonb,
    secrets text,
    enabled boolean DEFAULT true NOT NULL,
    source text DEFAULT 'manual'::text NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    auth_kind text DEFAULT 'token'::text NOT NULL
);

CREATE TABLE public.memory_candidates (
    id text NOT NULL,
    idempotency_key text NOT NULL,
    space_id text NOT NULL,
    origin_message_id text,
    statement text NOT NULL,
    slot_key text,
    value jsonb,
    provenance jsonb NOT NULL,
    evidence jsonb DEFAULT '[]'::jsonb NOT NULL,
    sensitive boolean DEFAULT false NOT NULL,
    policy_state text NOT NULL,
    claim_id text,
    conflicts_with text,
    created_at timestamp without time zone DEFAULT now(),
    resolved_at timestamp without time zone
);

CREATE TABLE public.memory_docs (
    id text NOT NULL,
    user_id text NOT NULL,
    project_id text,
    content text DEFAULT ''::text NOT NULL,
    prev_content text,
    version integer DEFAULT 0 NOT NULL,
    turns_since_consolidation integer DEFAULT 0 NOT NULL,
    updated_at timestamp without time zone DEFAULT now(),
    migrated_at timestamp without time zone
);

CREATE TABLE public.message_citations (
    id text NOT NULL,
    message_id text NOT NULL,
    ordinal integer NOT NULL,
    source_version_id text NOT NULL,
    fragment_id text NOT NULL,
    quote_snapshot text NOT NULL,
    locator_snapshot jsonb NOT NULL,
    title_snapshot text NOT NULL,
    created_at timestamp without time zone DEFAULT now()
);

CREATE TABLE public.message_effects (
    message_id text NOT NULL,
    tool_call_id text NOT NULL,
    producer_task_id text,
    tool_name text NOT NULL,
    input jsonb,
    failed boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    settled boolean DEFAULT true NOT NULL
);

CREATE TABLE public.messages (
    id text NOT NULL,
    chat_id text NOT NULL,
    role text NOT NULL,
    content text NOT NULL,
    platform text DEFAULT 'web'::text,
    telegram_message_id integer,
    metadata jsonb,
    created_at timestamp without time zone DEFAULT now(),
    parent_id text,
    untrusted_ingress boolean DEFAULT false NOT NULL
);

CREATE TABLE public.models (
    id text NOT NULL,
    source text NOT NULL,
    display_name text NOT NULL,
    "group" text,
    icon text,
    context_length integer,
    input_price numeric(20,12),
    output_price numeric(20,12),
    cache_read_price numeric(20,12),
    capabilities jsonb,
    enabled boolean DEFAULT false,
    featured boolean DEFAULT false,
    updated_at timestamp without time zone DEFAULT now(),
    cutoff text,
    open_weights boolean,
    cache_write_price numeric(20,12),
    first_seen_at timestamp without time zone DEFAULT now()
);

CREATE TABLE public.note_claims (
    note_id text NOT NULL,
    claim_id text NOT NULL,
    "position" integer DEFAULT 0 NOT NULL
);

CREATE TABLE public.note_version_evidence (
    id text NOT NULL,
    note_version_id text NOT NULL,
    block_ordinal integer NOT NULL,
    fragment_id text,
    message_id text,
    quote_snapshot text,
    locator_snapshot jsonb,
    relation text DEFAULT 'supports'::text NOT NULL,
    created_at timestamp without time zone DEFAULT now()
);

CREATE TABLE public.pending_elicitation (
    id text NOT NULL,
    chat_id text NOT NULL,
    message_id text NOT NULL,
    user_id text NOT NULL,
    form jsonb NOT NULL,
    answer jsonb,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.plugin_files (
    id text NOT NULL,
    install_id text NOT NULL,
    path text NOT NULL,
    content text NOT NULL
);

CREATE TABLE public.plugin_installs (
    id text NOT NULL,
    marketplace_id text NOT NULL,
    plugin_name text NOT NULL,
    version text,
    scope text DEFAULT 'system'::text NOT NULL,
    manifest jsonb DEFAULT '{}'::jsonb,
    installed_by text,
    created_at timestamp without time zone DEFAULT now(),
    user_id text,
    commit_sha text
);

CREATE TABLE public.plugin_marketplaces (
    id text NOT NULL,
    url text NOT NULL,
    name text NOT NULL,
    owner text,
    catalog jsonb DEFAULT '[]'::jsonb,
    refreshed_at timestamp without time zone DEFAULT now(),
    created_at timestamp without time zone DEFAULT now(),
    synthetic boolean DEFAULT false NOT NULL
);

CREATE TABLE public.projects (
    id text NOT NULL,
    user_id text NOT NULL,
    name text NOT NULL,
    description text,
    system_prompt text,
    default_model text,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    sandbox_network text DEFAULT 'none'::text,
    deleted_at timestamp without time zone,
    agent_profile jsonb
);

CREATE TABLE public.provider_configs (
    id text NOT NULL,
    user_id text NOT NULL,
    provider text NOT NULL,
    api_key text,
    base_url text,
    default_model text,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    label text,
    icon_slug text,
    shared boolean DEFAULT true,
    api_style text,
    sort_order integer DEFAULT 0 NOT NULL
);

CREATE TABLE public.session (
    id text NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    token text NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    ip_address text,
    user_agent text,
    user_id text NOT NULL
);

CREATE TABLE public.settings (
    key text NOT NULL,
    value text NOT NULL,
    is_encrypted boolean DEFAULT false,
    updated_at timestamp without time zone DEFAULT now()
);

CREATE TABLE public.skill_files (
    id text NOT NULL,
    skill_id text NOT NULL,
    path text NOT NULL,
    content text NOT NULL
);

CREATE TABLE public.skills (
    id text NOT NULL,
    scope text NOT NULL,
    user_id text,
    project_id text,
    name text NOT NULL,
    description text,
    body text NOT NULL,
    frontmatter jsonb DEFAULT '{}'::jsonb,
    source text DEFAULT 'manual'::text NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);

CREATE TABLE public.spaces (
    id text NOT NULL,
    type text NOT NULL,
    ref_id text NOT NULL,
    owner_user_id text NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    retired_at timestamp without time zone
);

CREATE TABLE public.tasks (
    id text NOT NULL,
    chat_id text NOT NULL,
    user_id text NOT NULL,
    status text DEFAULT 'queued'::text NOT NULL,
    error text,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    payload jsonb,
    lease_expires_at timestamp without time zone,
    heartbeat_at timestamp without time zone,
    worker_id text,
    cancel_requested boolean DEFAULT false,
    attempts integer DEFAULT 0,
    steers jsonb DEFAULT '[]'::jsonb NOT NULL
);

CREATE TABLE public.telegram_links (
    id text NOT NULL,
    user_id text NOT NULL,
    telegram_user_id bigint NOT NULL,
    telegram_username text,
    linked_at timestamp without time zone DEFAULT now(),
    active_chat_id text
);

CREATE TABLE public.tiers (
    id text NOT NULL,
    name text NOT NULL,
    limit_5h numeric(18,8),
    limit_week numeric(18,8),
    limit_month numeric(18,8),
    is_default boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now()
);

CREATE TABLE public.usage (
    id text NOT NULL,
    task_id text,
    message_id text,
    user_id text NOT NULL,
    provider text NOT NULL,
    model text NOT NULL,
    input_tokens integer DEFAULT 0,
    output_tokens integer DEFAULT 0,
    cached_input_tokens integer DEFAULT 0,
    cost_usd numeric(18,8),
    created_at timestamp without time zone DEFAULT now(),
    on_shared_key boolean DEFAULT false,
    pending boolean DEFAULT false NOT NULL,
    config_id text,
    purpose text
);

CREATE TABLE public."user" (
    id text NOT NULL,
    name text NOT NULL,
    email text NOT NULL,
    email_verified boolean DEFAULT false,
    image text,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    role text DEFAULT 'user'::text NOT NULL,
    locale text,
    tier_id text,
    tier_source text DEFAULT 'manual'::text NOT NULL,
    timezone text,
    status text DEFAULT 'active'::text NOT NULL,
    agent_profile jsonb
);

CREATE TABLE public.user_muted_resources (
    user_id text NOT NULL,
    kind text NOT NULL,
    resource_id text NOT NULL
);

CREATE TABLE public.vault_claims (
    id text NOT NULL,
    space_id text NOT NULL,
    statement text NOT NULL,
    slot_key text,
    value jsonb,
    kind text DEFAULT 'fact'::text NOT NULL,
    origin jsonb NOT NULL,
    review_status text DEFAULT 'unverified'::text NOT NULL,
    sensitive boolean DEFAULT false NOT NULL,
    valid_from timestamp without time zone,
    valid_to timestamp without time zone,
    recorded_at timestamp without time zone DEFAULT now() NOT NULL,
    revision integer DEFAULT 1 NOT NULL,
    supersedes text,
    superseded_at timestamp without time zone,
    approved_at timestamp without time zone,
    approved_by_user_id text,
    source_class text NOT NULL,
    prompt_access text GENERATED ALWAYS AS (
CASE
    WHEN sensitive THEN 'owner_only'::text
    WHEN (source_class = ANY (ARRAY['legacy_confirmed'::text, 'owner_authored'::text, 'user_direct'::text])) THEN 'manifest'::text
    WHEN (source_class = 'agent_inferred'::text) THEN 'memory_search'::text
    ELSE 'knowledge_search'::text
END) STORED NOT NULL,
    conflicts_with text,
    normalized_hash text,
    created_task_id text,
    expires_at timestamp without time zone,
    retired_at timestamp without time zone,
    last_used_at timestamp without time zone,
    CONSTRAINT ck_vault_claims_source_class CHECK ((source_class = ANY (ARRAY['legacy_confirmed'::text, 'owner_authored'::text, 'user_direct'::text, 'agent_inferred'::text, 'untrusted_derived'::text])))
);

CREATE TABLE public.vault_edges (
    id text NOT NULL,
    space_id text NOT NULL,
    from_node_id text NOT NULL,
    to_node_id text NOT NULL,
    relation text NOT NULL,
    "position" integer DEFAULT 0 NOT NULL,
    created_by jsonb NOT NULL,
    origin_message_id text,
    origin_fragment_id text,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    CONSTRAINT ck_vault_edges_not_self CHECK ((from_node_id <> to_node_id)),
    CONSTRAINT ck_vault_edges_relation CHECK ((relation = ANY (ARRAY['contains'::text, 'references'::text, 'derived_from'::text])))
);

CREATE TABLE public.vault_nodes (
    id text NOT NULL,
    space_id text NOT NULL,
    kind text NOT NULL,
    pinned boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    CONSTRAINT ck_vault_nodes_kind CHECK ((kind = ANY (ARRAY['note'::text, 'claim'::text, 'source'::text])))
);

CREATE TABLE public.vault_note_versions (
    id text NOT NULL,
    note_id text NOT NULL,
    revision integer NOT NULL,
    title text NOT NULL,
    body_markdown text NOT NULL,
    source_class text NOT NULL,
    sensitive boolean DEFAULT false NOT NULL,
    prompt_access text GENERATED ALWAYS AS (
CASE
    WHEN sensitive THEN 'owner_only'::text
    WHEN (source_class = ANY (ARRAY['legacy_confirmed'::text, 'owner_authored'::text, 'user_direct'::text])) THEN 'manifest'::text
    WHEN (source_class = 'agent_inferred'::text) THEN 'memory_search'::text
    ELSE 'knowledge_search'::text
END) STORED NOT NULL,
    provenance jsonb NOT NULL,
    created_task_id text,
    stale_since timestamp without time zone,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_vnote_versions_source_class CHECK ((source_class = ANY (ARRAY['legacy_confirmed'::text, 'owner_authored'::text, 'user_direct'::text, 'agent_inferred'::text, 'untrusted_derived'::text])))
);

CREATE TABLE public.vault_notes (
    id text NOT NULL,
    space_id text NOT NULL,
    title text NOT NULL,
    body text DEFAULT ''::text NOT NULL,
    kind text DEFAULT 'note'::text NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    topic_key text,
    expires_at timestamp without time zone,
    retired_at timestamp without time zone,
    last_used_at timestamp without time zone,
    current_version_id text,
    current_revision integer DEFAULT 1 NOT NULL,
    section text DEFAULT 'topic'::text NOT NULL,
    CONSTRAINT ck_vnotes_section CHECK ((section = ANY (ARRAY['you'::text, 'topic'::text, 'area'::text, 'person'::text])))
);

CREATE TABLE public.vault_search_documents (
    id text NOT NULL,
    space_id text NOT NULL,
    node_id text NOT NULL,
    fragment_id text DEFAULT ''::text NOT NULL,
    kind text NOT NULL,
    title text DEFAULT ''::text NOT NULL,
    owner_text text NOT NULL,
    model_text text,
    norm_title text GENERATED ALWAYS AS (lower(btrim(regexp_replace(COALESCE(title, ''::text), '[[:space:]\u00A0\u1680\u2000-\u200A\u2028\u2029\u202F\u205F\u3000\uFEFF]+'::text, ' '::text, 'g'::text)))) STORED NOT NULL,
    norm_owner_text text GENERATED ALWAYS AS (lower(btrim(regexp_replace(COALESCE(owner_text, ''::text), '[[:space:]\u00A0\u1680\u2000-\u200A\u2028\u2029\u202F\u205F\u3000\uFEFF]+'::text, ' '::text, 'g'::text)))) STORED NOT NULL,
    norm_model_text text GENERATED ALWAYS AS (lower(btrim(regexp_replace(model_text, '[[:space:]\u00A0\u1680\u2000-\u200A\u2028\u2029\u202F\u205F\u3000\uFEFF]+'::text, ' '::text, 'g'::text)))) STORED,
    owner_tsv tsvector GENERATED ALWAYS AS (to_tsvector('simple'::regconfig, ((title || ' '::text) || owner_text))) STORED,
    model_tsv tsvector GENERATED ALWAYS AS (to_tsvector('simple'::regconfig, ((title || ' '::text) || COALESCE(model_text, ''::text)))) STORED,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_vsearch_kind CHECK ((kind = ANY (ARRAY['claim'::text, 'note'::text, 'source'::text, 'fragment'::text])))
);

CREATE TABLE public.verification (
    id text NOT NULL,
    identifier text NOT NULL,
    value text NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);

ALTER TABLE ONLY drizzle.__drizzle_migrations ALTER COLUMN id SET DEFAULT nextval('drizzle.__drizzle_migrations_id_seq'::regclass);

INSERT INTO drizzle.__drizzle_migrations VALUES (1, 'b68d19433de65d9ca09bf3e6037a27b12ae6bc7565f1c022a61164dce87b09f7', 1774033712316);
INSERT INTO drizzle.__drizzle_migrations VALUES (2, '9f2ae27566717a2f79f06fd51b20ba050aa8263c172dc7a2987ca14470957c26', 1774434288220);
INSERT INTO drizzle.__drizzle_migrations VALUES (3, '6a089636f3dbe634785601f2d6db50b8055d666807865f9078c6f3f98b4b37b2', 1774434994078);
INSERT INTO drizzle.__drizzle_migrations VALUES (4, '9388838a088e8923c6265d3398f5a79b4979372abaea9c476d5441a2f1efe7f0', 1780920774100);
INSERT INTO drizzle.__drizzle_migrations VALUES (5, '44006e8fd562dfb23f2c343f2791be07a195da8a5a2ca453d6eee6c176eb4b68', 1780921610181);
INSERT INTO drizzle.__drizzle_migrations VALUES (6, '84d9e9ef03873d5bca284f46e266edd9f15eb708a2bbd8474a29b461cd400e4d', 1781007512030);
INSERT INTO drizzle.__drizzle_migrations VALUES (7, 'bc985c00a00b93c04a14b1671a5ed5811f95059d1342b8712424e5071e9949c2', 1781035049900);
INSERT INTO drizzle.__drizzle_migrations VALUES (8, 'dce17548e69b24881359b2b16bfa4ebe5650eb2b078a81c9ebe623e89d8b7d3f', 1781535900686);
INSERT INTO drizzle.__drizzle_migrations VALUES (9, 'cb2a5f811198f5045032e2c0ca146b6f009a0436dead94a688ad2b8bfee28740', 1781538079708);
INSERT INTO drizzle.__drizzle_migrations VALUES (10, '96cf1ed9fce50d74e7ed7bfc1b9fa13d3971246e1d36449def5ada2208850296', 1781540086945);
INSERT INTO drizzle.__drizzle_migrations VALUES (11, '94d209457e7f7abadad6aef2fae1acd79aea637d4cd8a05d5486a523f04130f5', 1781544089332);
INSERT INTO drizzle.__drizzle_migrations VALUES (12, 'bf5e3cfa221d574dc5be81e744965013e9f15c243d60633538e70a6643c05e7c', 1781544753935);
INSERT INTO drizzle.__drizzle_migrations VALUES (13, '6465beac1cb4c9ee90adad16c6e5d7f0dbabde84243c25b8fc7208c371c58223', 1781949568340);
INSERT INTO drizzle.__drizzle_migrations VALUES (14, 'd18c938318c37f76d6f33d2d1ca52a499db67565ce8d3e1faf8f5592f06d2e5f', 1781952292649);
INSERT INTO drizzle.__drizzle_migrations VALUES (15, '6b052b908b2676f68ec93454ba73dae4859beaf64baa02d9f95b50fe4d286390', 1781952300000);
INSERT INTO drizzle.__drizzle_migrations VALUES (16, 'c66d54675c4c4adb20b4e954ce80d88d7149d1840bbd901026ff4e87345374d5', 1782044977103);
INSERT INTO drizzle.__drizzle_migrations VALUES (17, 'ebd223ad5dbb3095d67d697fd40b3ff97f7f35b0540d4ea063eb688ed091fc26', 1782403200000);
INSERT INTO drizzle.__drizzle_migrations VALUES (18, 'd34fa4570ea379004bd3c0e89e2f36973cf2775975da667063b9640a51f5493a', 1782403200001);
INSERT INTO drizzle.__drizzle_migrations VALUES (19, 'e2c9907d96d68c3f457bcfc22dc7c2f436f938101e436a1146fe7c6ff5afe887', 1782403200002);
INSERT INTO drizzle.__drizzle_migrations VALUES (20, 'c54e9fe60dc17a2c0eb5ce5fac4372964fde61461b869381d85dc3c5ea4ffe76', 1782403200003);
INSERT INTO drizzle.__drizzle_migrations VALUES (21, 'c6c07a8b94d20d1784fa37952407da91db608792ca6b13a4ca36ce2204e7b42c', 1782403200004);
INSERT INTO drizzle.__drizzle_migrations VALUES (22, '986513d84eb95184509fec35ab1f9bf4cb1127ecc0456c9676684d69c269fd89', 1782403200005);
INSERT INTO drizzle.__drizzle_migrations VALUES (23, 'e566045df05162da5cc6843c777be2baaea94fdf8cfaa07c4060b68176ef12ac', 1782403200006);
INSERT INTO drizzle.__drizzle_migrations VALUES (24, 'a4b8c37e0c3ba5d2de22472ac4b83a6e82a16c74a7c07d8472fa4dbb9d86b41b', 1782403200007);
INSERT INTO drizzle.__drizzle_migrations VALUES (25, '578192dca427810934b10a032761677775897ee3a43745ff7f18398b7310f279', 1782403200008);
INSERT INTO drizzle.__drizzle_migrations VALUES (26, '700ae4471dea2596fe8dc63e842cbcf55d83ec523a6d2571e1be62bdc71e62be', 1782403200009);
INSERT INTO drizzle.__drizzle_migrations VALUES (27, '44b5a998384e2d2e483c1e7078fff636805e92e7d9336f3cb53c48d147604a74', 1782403200010);
INSERT INTO drizzle.__drizzle_migrations VALUES (28, '974d41a9216650ac92c600fffbb8126824843539b3ad5d0d942fc042313975ec', 1782403200011);
INSERT INTO drizzle.__drizzle_migrations VALUES (29, '2dae298103d822c8a3fba1fd1ea2926732f64bc8781d25289e02f51ed9c785e8', 1782403200012);
INSERT INTO drizzle.__drizzle_migrations VALUES (30, '308d418e5a90b5cdfed370e029740dbf78cd10448ad5b0fbfc9b692a676bb240', 1782403200013);
INSERT INTO drizzle.__drizzle_migrations VALUES (31, 'a0e52a18a930776005a26212bfa60effbbd10ece8dc7f0c3c17a630eaff7cdc7', 1782403200014);
INSERT INTO drizzle.__drizzle_migrations VALUES (32, 'b5b340e6392c895a4556eacab95ea49972b1091c4ff6d04a4484d8ac57227e87', 1782416215973);
INSERT INTO drizzle.__drizzle_migrations VALUES (33, 'cff42055fddc1a139ebc6ce043bfac0899bbc88c43cfa5656b5522cc39c7cbf9', 1782476269117);
INSERT INTO drizzle.__drizzle_migrations VALUES (34, '15c44a54c43edfbd4d0c8d9b43ac2361b41491e9c881a45409b4b9668bcc80df', 1782476284538);
INSERT INTO drizzle.__drizzle_migrations VALUES (35, '023546c114c93447be1a54657d16744e4cab85f7733a39d92cf53b08ff3dabee', 1782577646875);
INSERT INTO drizzle.__drizzle_migrations VALUES (36, '58dfbf1c8ee2da016a9993249e77afeae285e6e959f77809c9ce1668a6ff9d7d', 1782589216505);
INSERT INTO drizzle.__drizzle_migrations VALUES (37, '6fa0d19543aca2361e652ac358f32623f7a86bbaef1e266700333f373eee0c50', 1782592212079);
INSERT INTO drizzle.__drizzle_migrations VALUES (38, '19f57ab294f8da268ee4311490f0d7a912b98efc5d18e3b902ccfe1e9a394fe2', 1782942328066);
INSERT INTO drizzle.__drizzle_migrations VALUES (39, '033e4d9a2afb168d6d4114ef24e01cfb9e44496ba4e54182e3f1b6e3ca26e12a', 1783001091929);
INSERT INTO drizzle.__drizzle_migrations VALUES (40, '1a94624ca6353421b30bcb5896d3c6a6e4c81c960c38200581b3b437c4871400', 1783003290939);
INSERT INTO drizzle.__drizzle_migrations VALUES (41, '15517f5b79cbdb0389d55cd7724bd2faf5d213bd8ff8601ac0671fdc08ef28f4', 1783097721572);
INSERT INTO drizzle.__drizzle_migrations VALUES (42, '0b8b9bbb5c109b6d9c0f97b4c2373c16255daf95b7d1501ee324a4962bea9a20', 1783613552422);
INSERT INTO drizzle.__drizzle_migrations VALUES (43, 'e8cb1c7ef5d4d7180eb17a4229150c84ddfe29d396cc4e72d34ecfb59f00440c', 1783682298429);
INSERT INTO drizzle.__drizzle_migrations VALUES (44, '6057d4d6952d657d3641ef587689689bdbb44b3fbe78156c2b0f6ebb1e3fe3f3', 1783947525922);
INSERT INTO drizzle.__drizzle_migrations VALUES (45, 'fe62afd820d59c9c6748ccdbcc5643b5c0e0b3df2bdc3adce9eef6f103de88a5', 1784209158069);
INSERT INTO drizzle.__drizzle_migrations VALUES (46, '3ebe3e3d34fe73e6979e9ac15b5051bde409c59daf62cd6953ffabfa74d3ea60', 1784464105595);
INSERT INTO drizzle.__drizzle_migrations VALUES (47, '70239f4f384ce073ab9a1622bb493addabfe476917e37108b62ceae6eca44eca', 1784918086432);
INSERT INTO drizzle.__drizzle_migrations VALUES (48, '4cc120f67da15b938328fd23811b3763f21908bd911c28a323d9259315471370', 1784966182014);
INSERT INTO drizzle.__drizzle_migrations VALUES (49, '63f537100b0d4f7c53a59e94ee20ed2a372c429792756209bf36f334f2b064e6', 1785503422368);
INSERT INTO drizzle.__drizzle_migrations VALUES (50, 'a6e9eedbec714e8bdf210838b929e2ce6d20e44941f6ef84161bad79385a1025', 1786694773608);
INSERT INTO drizzle.__drizzle_migrations VALUES (51, '00d580f43d558c65113ded6dc73ed3f15e25b9279d1dd4e51be27a82f21a5107', 1786734104792);
INSERT INTO drizzle.__drizzle_migrations VALUES (52, '0502e3ade1cbf09a2e02f6eafd59147daa997b0346c42014b25570b10cf27043', 1786949007201);
INSERT INTO drizzle.__drizzle_migrations VALUES (53, 'eca0d29da0ca8fead4c310f9b6263e4c721d6ee01ea20bc367e446725764f7e8', 1787252620833);
INSERT INTO drizzle.__drizzle_migrations VALUES (54, '8ea33fbb6465d259ef42cab84df0fa28fc70b84e557304632e440ab30eaddfa8', 1787416014340);
INSERT INTO drizzle.__drizzle_migrations VALUES (55, '722b4f72ef1de8f49b3a3e8906380c765acf5c8876ec203c93d367aeecccd88a', 1787482760188);
INSERT INTO drizzle.__drizzle_migrations VALUES (56, '485b6814cf012b48a02d8b43ad2be28a5baf56f3a40fc0d8a669bb2142bc43d9', 1788025642821);
INSERT INTO drizzle.__drizzle_migrations VALUES (57, '118724c347ff50b69c25bb6cf95b856920004dc12079183ac8a8a86c0228679f', 1788080926884);
INSERT INTO drizzle.__drizzle_migrations VALUES (58, 'd795015beb6bb7827158ad5203b2d74a9f97a42c8b3545542cf208bdd771b0a1', 1788091860559);
INSERT INTO drizzle.__drizzle_migrations VALUES (59, '3b33dbc240e12d4fff34de124dd87224c7e3241191f855a26e7b48be4b2aea3f', 1788106907284);
INSERT INTO drizzle.__drizzle_migrations VALUES (60, '454ad36a1824ee6e80bfdfa3a8968e783bc67a1ecfd556714937de55b6d33ee3', 1788125449770);
INSERT INTO drizzle.__drizzle_migrations VALUES (61, 'b591bd0586d68d8a3872decc37693e7586db026593f620a384579a2226361a23', 1788127702879);
INSERT INTO drizzle.__drizzle_migrations VALUES (62, '82f71d3d60fd832a425a5d5cda0232ddad864a0769beed98743e6939db1af717', 1788130121997);
INSERT INTO drizzle.__drizzle_migrations VALUES (63, 'ff22ad973371e7f622a275f96e10b5d011ed05d8c454ea99eaaaba2b05b4ce48', 1788133158929);
INSERT INTO drizzle.__drizzle_migrations VALUES (64, 'ff0ec1454d7ab7a40f38ac015e93e9246508f2543aef8c718a50b908337b53c7', 1788133703193);
INSERT INTO drizzle.__drizzle_migrations VALUES (65, 'ac9fd6aea19969fc26b9cc5a4686757d3c3b6ba317002e366a46189b2383fce1', 1788134256734);
INSERT INTO drizzle.__drizzle_migrations VALUES (66, '4c830ddee9c541778a7916137078e64e687f621b9d6111a22407113c5f37c8cf', 1788144525516);
INSERT INTO drizzle.__drizzle_migrations VALUES (67, '290676372cabb46a652b25e7574c759e55d0b93dd2026275c0add637b8fbea35', 1788145726952);
INSERT INTO drizzle.__drizzle_migrations VALUES (68, '6668c89e3c2efa4f12ce9350016ab3837a0e71447baf8b882006dedc1df1a3db', 1788150038536);
INSERT INTO drizzle.__drizzle_migrations VALUES (69, '02a298efdb8b5140d3aa8a4d414c584998b973df60788bcf50d6794efa941546', 1788150939230);
INSERT INTO drizzle.__drizzle_migrations VALUES (70, '9fac8a745adcb742ad409f227a2426a6dde29fdf3c685e1a4f4a11a1e1d48851', 1788353765215);
INSERT INTO drizzle.__drizzle_migrations VALUES (71, '59dc7e39ef4be53eab8a9e64344c8e61f5e166418edbdff35ce1ca6a087b49bb', 1788358900000);
INSERT INTO drizzle.__drizzle_migrations VALUES (72, '79bad4c7bb1cc8b74e0c53eb7afa19b7142a4974afdf01b6d88123ba991f79b4', 1788602524321);
INSERT INTO drizzle.__drizzle_migrations VALUES (73, '808f202f4868af7ac9441f43f07ff477ee4a0c6bd3a03d4aa8a40d6b7a7c968b', 1788615588318);
INSERT INTO drizzle.__drizzle_migrations VALUES (74, 'dcf59d13f8f9cc036a32529f0ead044dc8ae292bd2868f62bcce1d6e9d407bd2', 1788724399742);
INSERT INTO drizzle.__drizzle_migrations VALUES (75, '765253c8a974e38e9b1a41ef7f128f6860ea8cdbeb4ae152aca904b59f87aca9', 1788729533279);
INSERT INTO drizzle.__drizzle_migrations VALUES (76, '5ec527f5deefbdec985aab05ad09b3e81738e38d868dba1ce34abb9d828b1d28', 1788764846581);
INSERT INTO drizzle.__drizzle_migrations VALUES (77, '5106c268bb8ef07eb949730c7f255041ae9da528abcdbb234daa72842e2136b5', 1788767218054);
INSERT INTO drizzle.__drizzle_migrations VALUES (78, '10208c876e63a3174ce212c2432c57119bc96c9f8c7c2b65a4b128e8543e5134', 1788772250759);
INSERT INTO drizzle.__drizzle_migrations VALUES (79, 'f102b24031869f4744653eed34a48b97008bdd1292306cdc48d9288dbb76f337', 1788773804547);

INSERT INTO public.chats VALUES ('up-c1', 'up-user', NULL, 'Fixture up-c1', NULL, false, false, '2026-09-20 10:00:00', '2026-09-20 10:00:00', 'c1a2', 'web', 'private', NULL, NULL, NULL);
INSERT INTO public.chats VALUES ('up-c2', 'up-user', NULL, 'Fixture up-c2', NULL, false, false, '2026-09-20 10:05:00', '2026-09-20 10:05:00', 'c2a3', 'web', 'private', NULL, NULL, NULL);
INSERT INTO public.chats VALUES ('up-c3', 'up-user', NULL, 'Fixture up-c3', NULL, false, false, '2026-09-20 10:12:00', '2026-09-20 10:12:00', 'c3a2', 'web', 'private', NULL, NULL, NULL);
INSERT INTO public.chats VALUES ('up-c4', 'up-user', NULL, 'Fixture up-c4', NULL, false, false, '2026-09-20 10:17:00', '2026-09-20 10:17:00', 'c4a1', 'web', 'private', NULL, NULL, NULL);
INSERT INTO public.chats VALUES ('up-c5', 'up-user', NULL, 'Fixture up-c5', NULL, false, false, '2026-09-20 10:20:00', '2026-09-20 10:20:00', 'c5a1', 'web', 'private', NULL, NULL, NULL);
INSERT INTO public.chats VALUES ('up-c6', 'up-admin', NULL, 'Fixture up-c6', NULL, false, false, '2026-09-20 10:23:00', '2026-09-20 10:23:00', 'c6a1', 'web', 'private', NULL, NULL, NULL);
INSERT INTO public.chats VALUES ('up-c7', 'up-user', NULL, 'Fixture up-c7', NULL, false, false, '2026-09-20 10:26:00', '2026-09-20 10:26:00', 'c7u1', 'web', 'private', NULL, NULL, NULL);

INSERT INTO public.messages VALUES ('c1u1', 'up-c1', 'user', 'List the files', 'web', NULL, NULL, '2026-09-20 10:01:00', NULL, false);
INSERT INTO public.messages VALUES ('c1a1', 'up-c1', 'assistant', 'Here they are.', 'web', NULL, '{"parts": [{"text": "Looking.", "type": "text"}, {"id": "call_c1_1", "name": "bash", "type": "tool-call", "input": {"command": "ls"}}, {"id": "call_c1_1", "name": "bash", "type": "tool-result", "output": {"stdout": "a.csv"}}, {"id": "call_c1_2", "name": "nope", "type": "tool-call", "input": "{bad"}, {"id": "call_c1_2", "name": "nope", "type": "tool-error", "error": "Invalid input", "invalid": true}, {"text": "Here they are.", "type": "text"}], "status": "completed", "steers": [{"at": "2026-09-20T10:00:30.000Z", "id": "s1", "text": "only csv"}], "taskId": "t-c1a1"}', '2026-09-20 10:02:00', 'c1u1', false);
INSERT INTO public.messages VALUES ('c1u2', 'up-c1', 'user', 'Thanks, and the old way?', 'web', NULL, NULL, '2026-09-20 10:03:00', 'c1a1', false);
INSERT INTO public.messages VALUES ('c1a2', 'up-c1', 'assistant', 'Done the old way.', 'web', NULL, '{"status": "completed", "taskId": "t-c1a2", "toolCalls": [{"id": "call_c1_3", "name": "bash", "input": {"command": "pwd"}}], "toolResults": [{"id": "call_c1_3", "output": "/workspace"}]}', '2026-09-20 10:04:00', 'c1u2', false);
INSERT INTO public.messages VALUES ('c1a1b', 'up-c1', 'assistant', 'An older answer.', 'web', NULL, '{"parts": [{"text": "An older answer.", "type": "text"}], "status": "completed"}', '2026-09-20 10:00:10', 'c1u1', false);
INSERT INTO public.messages VALUES ('c2u1', 'up-c2', 'user', 'Delete the report', 'web', NULL, NULL, '2026-09-20 10:06:00', NULL, false);
INSERT INTO public.messages VALUES ('c2a1', 'up-c2', 'assistant', '', 'web', NULL, '{"parts": [{"id": "call_c2_a", "name": "delete_file", "type": "tool-call", "input": {"path": "report.pdf"}, "approval": {"id": "apr-c2-a", "reason": "keep it", "approved": false}}], "status": "completed", "taskId": "t-c2a1"}', '2026-09-20 10:07:00', 'c2u1', false);
INSERT INTO public.messages VALUES ('c2u2', 'up-c2', 'user', 'Then archive it', 'web', NULL, NULL, '2026-09-20 10:08:00', 'c2a1', false);
INSERT INTO public.messages VALUES ('c2a2', 'up-c2', 'assistant', 'Archived.', 'web', NULL, '{"parts": [{"id": "call_c2_b", "name": "archive_file", "type": "tool-call", "input": {"path": "report.pdf"}, "approval": {"id": "apr-c2-b", "approved": true}}, {"id": "call_c2_b", "name": "archive_file", "type": "tool-result", "output": {"ok": true}}, {"text": "Archived.", "type": "text"}], "status": "completed", "taskId": "t-c2a2"}', '2026-09-20 10:09:00', 'c2u2', false);
INSERT INTO public.messages VALUES ('c2u3', 'up-c2', 'user', 'Good', 'web', NULL, NULL, '2026-09-20 10:10:00', 'c2a2', false);
INSERT INTO public.messages VALUES ('c2a3', 'up-c2', 'assistant', 'Anything else?', 'web', NULL, '{"parts": [{"text": "Anything else?", "type": "text"}], "status": "completed", "taskId": "t-c2a3"}', '2026-09-20 10:11:00', 'c2u3', false);
INSERT INTO public.messages VALUES ('c3u1', 'up-c3', 'user', 'Send the email', 'web', NULL, NULL, '2026-09-20 10:13:00', NULL, false);
INSERT INTO public.messages VALUES ('c3a1', 'up-c3', 'assistant', '', 'web', NULL, '{"parts": [{"id": "call_c3_a", "name": "send_email", "type": "tool-call", "input": {"to": "team@example.com"}, "approval": {"id": "apr-c3-a"}}], "status": "awaiting_approval", "taskId": "t-c3a1"}', '2026-09-20 10:14:00', 'c3u1', false);
INSERT INTO public.messages VALUES ('c3u2', 'up-c3', 'user', 'Never mind, summarize instead', 'web', NULL, NULL, '2026-09-20 10:15:00', 'c3a1', false);
INSERT INTO public.messages VALUES ('c3a2', 'up-c3', 'assistant', 'Summary.', 'web', NULL, '{"parts": [{"text": "Summary.", "type": "text"}], "status": "completed", "taskId": "t-c3a2"}', '2026-09-20 10:16:00', 'c3u2', false);
INSERT INTO public.messages VALUES ('c4u1', 'up-c4', 'user', 'Push the change', 'web', NULL, NULL, '2026-09-20 10:18:00', NULL, false);
INSERT INTO public.messages VALUES ('c4a1', 'up-c4', 'assistant', '', 'web', NULL, '{"parts": [{"text": "Pushing needs your OK.", "type": "text"}, {"id": "call_c4_a", "name": "git_push", "type": "tool-call", "input": {"branch": "main"}, "approval": {"id": "apr-c4-a"}}], "status": "awaiting_approval", "taskId": "t-c4a1"}', '2026-09-20 10:19:00', 'c4u1', false);
INSERT INTO public.messages VALUES ('c5u1', 'up-c5', 'user', 'Convert the file', 'web', NULL, NULL, '2026-09-20 10:21:00', NULL, false);
INSERT INTO public.messages VALUES ('c5a1', 'up-c5', 'assistant', '', 'web', NULL, '{"parts": [{"text": "Converting the file…", "type": "text"}, {"id": "call_c5_a", "name": "bash", "type": "tool-call", "input": {"command": "soffice --convert-to pdf a.docx"}}], "status": "running", "taskId": "t-c5-dead"}', '2026-09-20 10:22:00', 'c5u1', false);
INSERT INTO public.messages VALUES ('c6u1', 'up-c6', 'user', 'Think hard', 'web', NULL, NULL, '2026-09-20 10:24:00', NULL, false);
INSERT INTO public.messages VALUES ('c6a1', 'up-c6', 'assistant', '', 'web', NULL, '{"parts": [{"text": "Thinking", "type": "text"}], "status": "running", "taskId": "t-c6-live"}', '2026-09-20 10:25:00', 'c6u1', false);
INSERT INTO public.messages VALUES ('c7u1', 'up-c7', 'user', 'Queued question', 'web', NULL, NULL, '2026-09-20 10:27:00', NULL, false);

INSERT INTO public.provider_configs VALUES ('up-pc', 'up-admin', 'openrouter', 'c7561264925a34f082aa89cc6377fbbc:fb8c0718c4d0121616b36301ef0747ea:dd409a5923c936ba25d1722eeb9199bcba957f90d29cf34be4', NULL, NULL, true, '2026-09-20 09:00:00', '2026-09-20 09:00:00', NULL, NULL, true, NULL, 0);

INSERT INTO public.tasks VALUES ('t-c1a1', 'up-c1', 'up-user', 'completed', NULL, '2026-09-20 10:00:00', '2026-09-20 10:00:00', NULL, NULL, NULL, NULL, false, 0, '[]');
INSERT INTO public.tasks VALUES ('t-c1a2', 'up-c1', 'up-user', 'completed', NULL, '2026-09-20 10:00:00', '2026-09-20 10:00:00', NULL, NULL, NULL, NULL, false, 0, '[]');
INSERT INTO public.tasks VALUES ('t-c2a1', 'up-c2', 'up-user', 'completed', NULL, '2026-09-20 10:00:00', '2026-09-20 10:00:00', NULL, NULL, NULL, NULL, false, 0, '[]');
INSERT INTO public.tasks VALUES ('t-c2a2', 'up-c2', 'up-user', 'completed', NULL, '2026-09-20 10:00:00', '2026-09-20 10:00:00', NULL, NULL, NULL, NULL, false, 0, '[]');
INSERT INTO public.tasks VALUES ('t-c2a3', 'up-c2', 'up-user', 'completed', NULL, '2026-09-20 10:00:00', '2026-09-20 10:00:00', NULL, NULL, NULL, NULL, false, 0, '[]');
INSERT INTO public.tasks VALUES ('t-c3a1', 'up-c3', 'up-user', 'completed', NULL, '2026-09-20 10:00:00', '2026-09-20 10:00:00', NULL, NULL, NULL, NULL, false, 0, '[]');
INSERT INTO public.tasks VALUES ('t-c3a2', 'up-c3', 'up-user', 'completed', NULL, '2026-09-20 10:00:00', '2026-09-20 10:00:00', NULL, NULL, NULL, NULL, false, 0, '[]');
INSERT INTO public.tasks VALUES ('t-c4a1', 'up-c4', 'up-user', 'completed', NULL, '2026-09-20 10:00:00', '2026-09-20 10:00:00', NULL, NULL, NULL, NULL, false, 0, '[]');
INSERT INTO public.tasks VALUES ('t-c5-dead', 'up-c5', 'up-user', 'running', NULL, '2026-09-20 10:00:00', '2026-09-20 10:00:00', '{"chatId": "up-c5", "assistantMessageId": "c5a1"}', '2026-09-20 10:05:00', NULL, 'w-fixture', false, 0, '[]');
INSERT INTO public.tasks VALUES ('t-c6-live', 'up-c6', 'up-admin', 'running', NULL, '2026-09-20 10:00:00', '2026-09-20 10:00:00', '{"chatId": "up-c6", "assistantMessageId": "c6a1"}', '2100-01-01 00:00:00', NULL, 'w-fixture', false, 0, '[]');
INSERT INTO public.tasks VALUES ('t-c7-q', 'up-c7', 'up-user', 'queued', NULL, '2026-09-20 10:00:00', '2026-09-20 10:00:00', '{"chatId": "up-c7", "userMessageId": "c7u1"}', NULL, NULL, NULL, false, 0, '[]');

INSERT INTO public.tiers VALUES ('default', 'Default', NULL, NULL, NULL, true, '2026-10-01 09:30:44.504697');

INSERT INTO public.usage VALUES ('us-c1a1', 't-c1a1', NULL, 'up-user', 'openrouter', 'fixture/model', 0, 0, 0, 0.00120000, '2026-09-20 10:00:00', true, false, NULL, 'turn');
INSERT INTO public.usage VALUES ('h-c5', 't-c5-dead', NULL, 'up-user', 'openrouter', 'fixture/model', 0, 0, 0, 0.05000000, '2026-09-20 10:00:00', true, true, NULL, 'turn');
INSERT INTO public.usage VALUES ('h-c6', 't-c6-live', NULL, 'up-admin', 'openrouter', 'fixture/model', 0, 0, 0, 0.05000000, '2026-09-20 10:00:00', true, true, NULL, 'turn');
INSERT INTO public.usage VALUES ('h-c7', 't-c7-q', NULL, 'up-user', 'openrouter', 'fixture/model', 0, 0, 0, 0.05000000, '2026-09-20 10:00:00', true, true, NULL, 'turn');
INSERT INTO public.usage VALUES ('h-leak', 't-c1a2', NULL, 'up-user', 'openrouter', 'fixture/model', 0, 0, 0, 0.05000000, '2026-09-20 10:00:00', true, true, NULL, 'turn');
INSERT INTO public.usage VALUES ('h-orphan', 't-gone', NULL, 'up-user', 'openrouter', 'fixture/model', 0, 0, 0, 0.05000000, '2026-09-20 10:00:00', true, true, NULL, 'turn');

INSERT INTO public."user" VALUES ('up-admin', 'Admin', 'admin@fixture.invalid', false, NULL, '2026-09-20 09:00:00', '2026-09-20 09:00:00', 'admin', NULL, NULL, 'manual', NULL, 'active', NULL);
INSERT INTO public."user" VALUES ('up-user', 'User', 'user@fixture.invalid', false, NULL, '2026-09-20 09:00:00', '2026-09-20 09:00:00', 'user', NULL, NULL, 'manual', NULL, 'active', NULL);

SELECT pg_catalog.setval('drizzle.__drizzle_migrations_id_seq', 79, true);

ALTER TABLE ONLY drizzle.__drizzle_migrations
    ADD CONSTRAINT __drizzle_migrations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.attached_folders
    ADD CONSTRAINT attached_folders_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.audit_events
    ADD CONSTRAINT audit_events_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.automation_webhook_deliveries
    ADD CONSTRAINT automation_webhook_deliveries_automation_id_idempotency_key_pk PRIMARY KEY (automation_id, idempotency_key);

ALTER TABLE ONLY public.automations
    ADD CONSTRAINT automations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.automations
    ADD CONSTRAINT automations_webhook_token_unique UNIQUE (webhook_token);

ALTER TABLE ONLY public.capability_policies
    ADD CONSTRAINT capability_policies_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.chat_secrets
    ADD CONSTRAINT chat_secrets_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.chats
    ADD CONSTRAINT chats_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.chats
    ADD CONSTRAINT chats_share_token_unique UNIQUE (share_token);

ALTER TABLE ONLY public.claim_evidence
    ADD CONSTRAINT claim_evidence_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.knowledge_fragments
    ADD CONSTRAINT knowledge_fragments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.knowledge_source_versions
    ADD CONSTRAINT knowledge_source_versions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.knowledge_sources
    ADD CONSTRAINT knowledge_sources_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.link_codes
    ADD CONSTRAINT link_codes_pkey PRIMARY KEY (code);

ALTER TABLE ONLY public.manage_pending
    ADD CONSTRAINT manage_pending_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.mcp_oauth_clients
    ADD CONSTRAINT mcp_oauth_clients_pkey PRIMARY KEY (server_id);

ALTER TABLE ONLY public.mcp_oauth_states
    ADD CONSTRAINT mcp_oauth_states_pkey PRIMARY KEY (state);

ALTER TABLE ONLY public.mcp_oauth_tokens
    ADD CONSTRAINT mcp_oauth_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.mcp_servers
    ADD CONSTRAINT mcp_servers_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.memory_candidates
    ADD CONSTRAINT memory_candidates_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.memory_docs
    ADD CONSTRAINT memory_docs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.message_citations
    ADD CONSTRAINT message_citations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.message_effects
    ADD CONSTRAINT message_effects_message_id_tool_call_id_pk PRIMARY KEY (message_id, tool_call_id);

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.models
    ADD CONSTRAINT models_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.note_version_evidence
    ADD CONSTRAINT note_version_evidence_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.pending_elicitation
    ADD CONSTRAINT pending_elicitation_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.plugin_files
    ADD CONSTRAINT plugin_files_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.plugin_installs
    ADD CONSTRAINT plugin_installs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.plugin_marketplaces
    ADD CONSTRAINT plugin_marketplaces_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.provider_configs
    ADD CONSTRAINT provider_configs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.session
    ADD CONSTRAINT session_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.session
    ADD CONSTRAINT session_token_unique UNIQUE (token);

ALTER TABLE ONLY public.settings
    ADD CONSTRAINT settings_pkey PRIMARY KEY (key);

ALTER TABLE ONLY public.skill_files
    ADD CONSTRAINT skill_files_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.skills
    ADD CONSTRAINT skills_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.spaces
    ADD CONSTRAINT spaces_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.telegram_links
    ADD CONSTRAINT telegram_links_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.telegram_links
    ADD CONSTRAINT telegram_links_telegram_user_id_unique UNIQUE (telegram_user_id);

ALTER TABLE ONLY public.tiers
    ADD CONSTRAINT tiers_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.usage
    ADD CONSTRAINT usage_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_email_unique UNIQUE (email);

ALTER TABLE ONLY public.user_muted_resources
    ADD CONSTRAINT user_muted_resources_user_id_kind_resource_id_pk PRIMARY KEY (user_id, kind, resource_id);

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.vault_claims
    ADD CONSTRAINT vault_claims_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.vault_edges
    ADD CONSTRAINT vault_edges_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.vault_nodes
    ADD CONSTRAINT vault_nodes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.vault_note_versions
    ADD CONSTRAINT vault_note_versions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.vault_notes
    ADD CONSTRAINT vault_notes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.vault_search_documents
    ADD CONSTRAINT vault_search_documents_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.verification
    ADD CONSTRAINT verification_pkey PRIMARY KEY (id);

CREATE INDEX idx_attached_folders_session ON public.attached_folders USING btree (session_key);

CREATE INDEX idx_audit_log_action ON public.audit_log USING btree (action);

CREATE INDEX idx_audit_log_created ON public.audit_log USING btree (created_at);

CREATE INDEX idx_audit_space_created ON public.audit_events USING btree (space_id, created_at);

CREATE INDEX idx_automation_webhook_deliveries_created_at ON public.automation_webhook_deliveries USING btree (created_at);

CREATE INDEX idx_automations_due ON public.automations USING btree (next_run_at) WHERE (enabled = true);

CREATE INDEX idx_automations_user_id ON public.automations USING btree (user_id);

CREATE INDEX idx_capability_policies_scope ON public.capability_policies USING btree (scope);

CREATE INDEX idx_capability_policies_type ON public.capability_policies USING btree (capability_type);

CREATE INDEX idx_cev_claim ON public.claim_evidence USING btree (claim_id);

CREATE UNIQUE INDEX idx_chat_secrets_chat_name ON public.chat_secrets USING btree (chat_id, name);

CREATE INDEX idx_chats_project_id ON public.chats USING btree (project_id);

CREATE INDEX idx_chats_sidebar ON public.chats USING btree (user_id, archived, pinned, updated_at, id);

CREATE INDEX idx_chats_user_id ON public.chats USING btree (user_id);

CREATE INDEX idx_ksources_space ON public.knowledge_sources USING btree (space_id);

CREATE INDEX idx_ksv_source ON public.knowledge_source_versions USING btree (source_id);

CREATE INDEX idx_ksv_source_sha ON public.knowledge_source_versions USING btree (source_id, sha256);

CREATE INDEX idx_manage_pending_expires ON public.manage_pending USING btree (expires_at);

CREATE INDEX idx_mcand_unresolved ON public.memory_candidates USING btree (space_id) WHERE (resolved_at IS NULL);

CREATE INDEX idx_mcit_fragment ON public.message_citations USING btree (fragment_id);

CREATE INDEX idx_mcp_oauth_tokens_server ON public.mcp_oauth_tokens USING btree (server_id);

CREATE INDEX idx_mcp_oauth_tokens_user ON public.mcp_oauth_tokens USING btree (user_id);

CREATE INDEX idx_mcp_servers_project_id ON public.mcp_servers USING btree (project_id);

CREATE INDEX idx_mcp_servers_scope ON public.mcp_servers USING btree (scope);

CREATE INDEX idx_mcp_servers_user_id ON public.mcp_servers USING btree (user_id);

CREATE INDEX idx_memory_docs_user_id ON public.memory_docs USING btree (user_id);

CREATE INDEX idx_messages_chat_id ON public.messages USING btree (chat_id);

CREATE INDEX idx_messages_chat_role_created ON public.messages USING btree (chat_id, role, created_at);

CREATE INDEX idx_messages_content_fts ON public.messages USING gin (to_tsvector('simple'::regconfig, content));

CREATE INDEX idx_messages_created_at ON public.messages USING btree (created_at);

CREATE INDEX idx_messages_parent_id ON public.messages USING btree (parent_id);

CREATE INDEX idx_models_enabled ON public.models USING btree (enabled);

CREATE INDEX idx_models_group ON public.models USING btree ("group");

CREATE INDEX idx_note_claims_claim ON public.note_claims USING btree (claim_id);

CREATE INDEX idx_nve_fragment ON public.note_version_evidence USING btree (fragment_id);

CREATE INDEX idx_nve_version ON public.note_version_evidence USING btree (note_version_id);

CREATE INDEX idx_pending_elicitation_message ON public.pending_elicitation USING btree (message_id);

CREATE INDEX idx_plugin_files_install_id ON public.plugin_files USING btree (install_id);

CREATE INDEX idx_plugin_installs_marketplace ON public.plugin_installs USING btree (marketplace_id);

CREATE INDEX idx_plugin_installs_user ON public.plugin_installs USING btree (user_id);

CREATE INDEX idx_projects_deleted_at ON public.projects USING btree (deleted_at) WHERE (deleted_at IS NOT NULL);

CREATE INDEX idx_projects_user_id ON public.projects USING btree (user_id);

CREATE INDEX idx_provider_configs_user_id ON public.provider_configs USING btree (user_id);

CREATE INDEX idx_skill_files_skill_id ON public.skill_files USING btree (skill_id);

CREATE INDEX idx_skills_project_id ON public.skills USING btree (project_id);

CREATE INDEX idx_skills_scope ON public.skills USING btree (scope);

CREATE INDEX idx_skills_user_id ON public.skills USING btree (user_id);

CREATE INDEX idx_spaces_owner ON public.spaces USING btree (owner_user_id);

CREATE INDEX idx_tasks_chat_id ON public.tasks USING btree (chat_id);

CREATE INDEX idx_tasks_chat_status ON public.tasks USING btree (chat_id, status);

CREATE INDEX idx_tasks_status_created ON public.tasks USING btree (status, created_at);

CREATE INDEX idx_tasks_status_lease ON public.tasks USING btree (status, lease_expires_at);

CREATE INDEX idx_tasks_user_id_status ON public.tasks USING btree (user_id, status);

CREATE INDEX idx_telegram_links_tg_user_id ON public.telegram_links USING btree (telegram_user_id);

CREATE INDEX idx_tiers_is_default ON public.tiers USING btree (is_default);

CREATE INDEX idx_usage_config_created ON public.usage USING btree (config_id, created_at);

CREATE INDEX idx_usage_model ON public.usage USING btree (model);

CREATE INDEX idx_usage_task_pending ON public.usage USING btree (task_id, pending);

CREATE INDEX idx_usage_user_created ON public.usage USING btree (user_id, created_at);

CREATE INDEX idx_user_muted_user ON public.user_muted_resources USING btree (user_id);

CREATE INDEX idx_vault_edges_from ON public.vault_edges USING btree (space_id, from_node_id) WHERE (deleted_at IS NULL);

CREATE INDEX idx_vault_edges_to ON public.vault_edges USING btree (space_id, to_node_id) WHERE (deleted_at IS NULL);

CREATE INDEX idx_vault_nodes_space_kind ON public.vault_nodes USING btree (space_id, kind) WHERE (deleted_at IS NULL);

CREATE INDEX idx_vclaims_conflicts_with ON public.vault_claims USING btree (conflicts_with) WHERE (conflicts_with IS NOT NULL);

CREATE INDEX idx_vclaims_norm_hash ON public.vault_claims USING btree (space_id, normalized_hash) WHERE (superseded_at IS NULL);

CREATE INDEX idx_vclaims_prompt_access ON public.vault_claims USING btree (space_id, prompt_access) WHERE ((superseded_at IS NULL) AND (retired_at IS NULL));

CREATE INDEX idx_vclaims_slot ON public.vault_claims USING btree (space_id, slot_key);

CREATE INDEX idx_vclaims_space_head ON public.vault_claims USING btree (space_id, superseded_at);

CREATE INDEX idx_vclaims_supersedes ON public.vault_claims USING btree (supersedes);

CREATE INDEX idx_vnotes_space ON public.vault_notes USING btree (space_id);

CREATE UNIQUE INDEX uniq_kfrag_version_ordinal ON public.knowledge_fragments USING btree (version_id, ordinal);

CREATE UNIQUE INDEX uniq_live_vault_edge ON public.vault_edges USING btree (space_id, from_node_id, to_node_id, relation) WHERE (deleted_at IS NULL);

CREATE UNIQUE INDEX uniq_mcand_idem ON public.memory_candidates USING btree (idempotency_key);

CREATE UNIQUE INDEX uniq_mcit_msg_ordinal ON public.message_citations USING btree (message_id, ordinal);

CREATE UNIQUE INDEX uniq_memory_docs_user_global ON public.memory_docs USING btree (user_id) WHERE (project_id IS NULL);

CREATE UNIQUE INDEX uniq_memory_docs_user_project ON public.memory_docs USING btree (user_id, project_id);

CREATE UNIQUE INDEX uniq_note_claims ON public.note_claims USING btree (note_id, claim_id);

CREATE UNIQUE INDEX uniq_spaces_type_ref ON public.spaces USING btree (type, ref_id);

CREATE UNIQUE INDEX uniq_vault_nodes_space_id ON public.vault_nodes USING btree (space_id, id);

CREATE UNIQUE INDEX uniq_vclaims_one_successor ON public.vault_claims USING btree (supersedes) WHERE (supersedes IS NOT NULL);

CREATE UNIQUE INDEX uniq_vnote_versions_rev ON public.vault_note_versions USING btree (note_id, revision);

CREATE UNIQUE INDEX uniq_vnotes_memory_topic ON public.vault_notes USING btree (space_id, topic_key) WHERE (kind = 'memory_topic'::text);

CREATE UNIQUE INDEX uniq_vnotes_topic_title ON public.vault_notes USING btree (lower(btrim(regexp_replace(title, '[[:space:]]+'::text, ' '::text, 'g'::text))), space_id) WHERE (kind = 'memory_topic'::text);

CREATE UNIQUE INDEX uniq_vsearch_unit ON public.vault_search_documents USING btree (space_id, node_id, fragment_id);

CREATE UNIQUE INDEX uq_attached_folders_session_name ON public.attached_folders USING btree (session_key, name);

CREATE UNIQUE INDEX uq_capability_policies_project ON public.capability_policies USING btree (project_id, capability_type, capability_key) WHERE (scope = 'project'::text);

CREATE UNIQUE INDEX uq_capability_policies_system ON public.capability_policies USING btree (capability_type, capability_key) WHERE (scope = 'system'::text);

CREATE UNIQUE INDEX uq_capability_policies_user ON public.capability_policies USING btree (user_id, capability_type, capability_key) WHERE (scope = 'user'::text);

CREATE UNIQUE INDEX uq_plugin_installs_system ON public.plugin_installs USING btree (marketplace_id, plugin_name, scope) WHERE (user_id IS NULL);

CREATE UNIQUE INDEX uq_plugin_installs_user ON public.plugin_installs USING btree (marketplace_id, plugin_name, scope, user_id) WHERE (user_id IS NOT NULL);

CREATE UNIQUE INDEX uq_tasks_one_queued_per_chat ON public.tasks USING btree (chat_id) WHERE (status = 'queued'::text);

CREATE UNIQUE INDEX uq_usage_one_pending_per_task ON public.usage USING btree (task_id) WHERE pending;

CREATE INDEX vault_search_model_fts ON public.vault_search_documents USING gin (model_tsv);

CREATE INDEX vault_search_model_trgm ON public.vault_search_documents USING gin (norm_model_text public.gin_trgm_ops);

CREATE INDEX vault_search_owner_fts ON public.vault_search_documents USING gin (owner_tsv);

CREATE INDEX vault_search_owner_trgm ON public.vault_search_documents USING gin (norm_owner_text public.gin_trgm_ops);

CREATE INDEX vault_search_scope ON public.vault_search_documents USING btree (space_id, kind);

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_user_id_user_id_fk FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.attached_folders
    ADD CONSTRAINT attached_folders_user_id_user_id_fk FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.audit_events
    ADD CONSTRAINT audit_events_space_id_spaces_id_fk FOREIGN KEY (space_id) REFERENCES public.spaces(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_actor_id_user_id_fk FOREIGN KEY (actor_id) REFERENCES public."user"(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.automation_webhook_deliveries
    ADD CONSTRAINT automation_webhook_deliveries_automation_id_automations_id_fk FOREIGN KEY (automation_id) REFERENCES public.automations(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.automations
    ADD CONSTRAINT automations_project_id_projects_id_fk FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.automations
    ADD CONSTRAINT automations_user_id_user_id_fk FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.capability_policies
    ADD CONSTRAINT capability_policies_created_by_user_id_fk FOREIGN KEY (created_by) REFERENCES public."user"(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.capability_policies
    ADD CONSTRAINT capability_policies_project_id_projects_id_fk FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.capability_policies
    ADD CONSTRAINT capability_policies_user_id_user_id_fk FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.chat_secrets
    ADD CONSTRAINT chat_secrets_chat_id_chats_id_fk FOREIGN KEY (chat_id) REFERENCES public.chats(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.chat_secrets
    ADD CONSTRAINT chat_secrets_user_id_user_id_fk FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.chats
    ADD CONSTRAINT chats_active_leaf_id_messages_id_fk FOREIGN KEY (active_leaf_id) REFERENCES public.messages(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.chats
    ADD CONSTRAINT chats_project_id_projects_id_fk FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.chats
    ADD CONSTRAINT chats_user_id_user_id_fk FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.claim_evidence
    ADD CONSTRAINT claim_evidence_claim_id_vault_claims_id_fk FOREIGN KEY (claim_id) REFERENCES public.vault_claims(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.claim_evidence
    ADD CONSTRAINT claim_evidence_fragment_id_knowledge_fragments_id_fk FOREIGN KEY (fragment_id) REFERENCES public.knowledge_fragments(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.knowledge_fragments
    ADD CONSTRAINT knowledge_fragments_version_id_knowledge_source_versions_id_fk FOREIGN KEY (version_id) REFERENCES public.knowledge_source_versions(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.knowledge_sources
    ADD CONSTRAINT knowledge_source_node_fk FOREIGN KEY (space_id, id) REFERENCES public.vault_nodes(space_id, id);

ALTER TABLE ONLY public.knowledge_source_versions
    ADD CONSTRAINT knowledge_source_versions_source_id_knowledge_sources_id_fk FOREIGN KEY (source_id) REFERENCES public.knowledge_sources(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.knowledge_sources
    ADD CONSTRAINT knowledge_sources_space_id_spaces_id_fk FOREIGN KEY (space_id) REFERENCES public.spaces(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.link_codes
    ADD CONSTRAINT link_codes_user_id_user_id_fk FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.manage_pending
    ADD CONSTRAINT manage_pending_user_id_user_id_fk FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.mcp_oauth_clients
    ADD CONSTRAINT mcp_oauth_clients_server_id_mcp_servers_id_fk FOREIGN KEY (server_id) REFERENCES public.mcp_servers(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.mcp_oauth_states
    ADD CONSTRAINT mcp_oauth_states_server_id_mcp_servers_id_fk FOREIGN KEY (server_id) REFERENCES public.mcp_servers(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.mcp_oauth_states
    ADD CONSTRAINT mcp_oauth_states_user_id_user_id_fk FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.mcp_oauth_tokens
    ADD CONSTRAINT mcp_oauth_tokens_server_id_mcp_servers_id_fk FOREIGN KEY (server_id) REFERENCES public.mcp_servers(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.mcp_oauth_tokens
    ADD CONSTRAINT mcp_oauth_tokens_user_id_user_id_fk FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.mcp_servers
    ADD CONSTRAINT mcp_servers_project_id_projects_id_fk FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.mcp_servers
    ADD CONSTRAINT mcp_servers_user_id_user_id_fk FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.memory_candidates
    ADD CONSTRAINT memory_candidates_space_id_spaces_id_fk FOREIGN KEY (space_id) REFERENCES public.spaces(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.memory_docs
    ADD CONSTRAINT memory_docs_project_id_projects_id_fk FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.memory_docs
    ADD CONSTRAINT memory_docs_user_id_user_id_fk FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.message_citations
    ADD CONSTRAINT message_citations_fragment_id_knowledge_fragments_id_fk FOREIGN KEY (fragment_id) REFERENCES public.knowledge_fragments(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.message_citations
    ADD CONSTRAINT message_citations_message_id_messages_id_fk FOREIGN KEY (message_id) REFERENCES public.messages(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.message_citations
    ADD CONSTRAINT message_citations_source_version_id_knowledge_source_versions_i FOREIGN KEY (source_version_id) REFERENCES public.knowledge_source_versions(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.message_effects
    ADD CONSTRAINT message_effects_message_id_messages_id_fk FOREIGN KEY (message_id) REFERENCES public.messages(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_chat_id_chats_id_fk FOREIGN KEY (chat_id) REFERENCES public.chats(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_parent_id_messages_id_fk FOREIGN KEY (parent_id) REFERENCES public.messages(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.note_claims
    ADD CONSTRAINT note_claims_claim_id_vault_claims_id_fk FOREIGN KEY (claim_id) REFERENCES public.vault_claims(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.note_claims
    ADD CONSTRAINT note_claims_note_id_vault_notes_id_fk FOREIGN KEY (note_id) REFERENCES public.vault_notes(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.note_version_evidence
    ADD CONSTRAINT note_version_evidence_fragment_id_knowledge_fragments_id_fk FOREIGN KEY (fragment_id) REFERENCES public.knowledge_fragments(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.note_version_evidence
    ADD CONSTRAINT note_version_evidence_note_version_id_vault_note_versions_id_fk FOREIGN KEY (note_version_id) REFERENCES public.vault_note_versions(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.plugin_files
    ADD CONSTRAINT plugin_files_install_id_plugin_installs_id_fk FOREIGN KEY (install_id) REFERENCES public.plugin_installs(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.plugin_installs
    ADD CONSTRAINT plugin_installs_installed_by_user_id_fk FOREIGN KEY (installed_by) REFERENCES public."user"(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.plugin_installs
    ADD CONSTRAINT plugin_installs_marketplace_id_plugin_marketplaces_id_fk FOREIGN KEY (marketplace_id) REFERENCES public.plugin_marketplaces(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.plugin_installs
    ADD CONSTRAINT plugin_installs_user_id_user_id_fk FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_user_id_user_id_fk FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.provider_configs
    ADD CONSTRAINT provider_configs_user_id_user_id_fk FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.session
    ADD CONSTRAINT session_user_id_user_id_fk FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.skill_files
    ADD CONSTRAINT skill_files_skill_id_skills_id_fk FOREIGN KEY (skill_id) REFERENCES public.skills(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.skills
    ADD CONSTRAINT skills_project_id_projects_id_fk FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.skills
    ADD CONSTRAINT skills_user_id_user_id_fk FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_chat_id_chats_id_fk FOREIGN KEY (chat_id) REFERENCES public.chats(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_user_id_user_id_fk FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.telegram_links
    ADD CONSTRAINT telegram_links_active_chat_id_chats_id_fk FOREIGN KEY (active_chat_id) REFERENCES public.chats(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.telegram_links
    ADD CONSTRAINT telegram_links_user_id_user_id_fk FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.usage
    ADD CONSTRAINT usage_config_id_provider_configs_id_fk FOREIGN KEY (config_id) REFERENCES public.provider_configs(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.usage
    ADD CONSTRAINT usage_user_id_user_id_fk FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.user_muted_resources
    ADD CONSTRAINT user_muted_resources_user_id_user_id_fk FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.vault_claims
    ADD CONSTRAINT vault_claim_node_fk FOREIGN KEY (space_id, id) REFERENCES public.vault_nodes(space_id, id);

ALTER TABLE ONLY public.vault_claims
    ADD CONSTRAINT vault_claims_conflicts_with_fk FOREIGN KEY (space_id, conflicts_with) REFERENCES public.vault_nodes(space_id, id);

ALTER TABLE ONLY public.vault_claims
    ADD CONSTRAINT vault_claims_space_id_spaces_id_fk FOREIGN KEY (space_id) REFERENCES public.spaces(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.vault_edges
    ADD CONSTRAINT vault_edges_from_node_fk FOREIGN KEY (space_id, from_node_id) REFERENCES public.vault_nodes(space_id, id) ON DELETE CASCADE;

ALTER TABLE ONLY public.vault_edges
    ADD CONSTRAINT vault_edges_to_node_fk FOREIGN KEY (space_id, to_node_id) REFERENCES public.vault_nodes(space_id, id) ON DELETE CASCADE;

ALTER TABLE ONLY public.vault_nodes
    ADD CONSTRAINT vault_nodes_space_id_spaces_id_fk FOREIGN KEY (space_id) REFERENCES public.spaces(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.vault_notes
    ADD CONSTRAINT vault_note_node_fk FOREIGN KEY (space_id, id) REFERENCES public.vault_nodes(space_id, id);

ALTER TABLE ONLY public.vault_note_versions
    ADD CONSTRAINT vault_note_versions_note_id_vault_notes_id_fk FOREIGN KEY (note_id) REFERENCES public.vault_notes(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.vault_notes
    ADD CONSTRAINT vault_notes_current_version_id_vault_note_versions_id_fk FOREIGN KEY (current_version_id) REFERENCES public.vault_note_versions(id);

ALTER TABLE ONLY public.vault_notes
    ADD CONSTRAINT vault_notes_space_id_spaces_id_fk FOREIGN KEY (space_id) REFERENCES public.spaces(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.vault_search_documents
    ADD CONSTRAINT vault_search_doc_node_fk FOREIGN KEY (space_id, node_id) REFERENCES public.vault_nodes(space_id, id) ON DELETE CASCADE;

ALTER TABLE ONLY public.vault_search_documents
    ADD CONSTRAINT vault_search_documents_space_id_spaces_id_fk FOREIGN KEY (space_id) REFERENCES public.spaces(id) ON DELETE CASCADE;
